// test/manual/catalog-gen.ts
import { readFile, writeFile } from 'node:fs/promises';
import type { Block } from './types.js';

export function generateCatalog(registry: Map<string, Block>): string {
  const blocks = [...registry.values()].sort((a, b) => a.name.localeCompare(b.name));
  const lines: string[] = [];
  lines.push('# Manual Testing — Scenario Catalog');
  lines.push('');
  lines.push('> AUTO-GENERATED by `npm run test:manual:gen-catalog`. Do not edit by hand.');
  lines.push('> Source: `test/manual/scenarios/<block>.ts` `documentation` fields.');
  lines.push('');
  lines.push('| Block | Dependencies | Collections written |');
  lines.push('|---|---|---|');
  for (const b of blocks) {
    const deps = b.documentation.dependencies.length
      ? b.documentation.dependencies.join(', ')
      : '—';
    const cols = b.documentation.collectionsWritten.length
      ? b.documentation.collectionsWritten.join(', ')
      : '—';
    lines.push(`| \`${b.name}\` | ${deps} | ${cols} |`);
  }
  lines.push('');
  for (const b of blocks) {
    lines.push(`### \`${b.name}\``);
    lines.push('');
    lines.push(b.documentation.description);
    lines.push('');
    if (b.documentation.configExamples.length) {
      lines.push('**Config examples:**');
      lines.push('');
      for (const ex of b.documentation.configExamples) {
        lines.push(`- **${ex.label}**`);
        lines.push('  ```json');
        lines.push('  ' + JSON.stringify(ex.config, null, 2).split('\n').join('\n  '));
        lines.push('  ```');
      }
      lines.push('');
    }
    lines.push(`**Dependencies:** ${b.documentation.dependencies.join(', ') || '—'}`);
    lines.push('');
    lines.push(`**Collections written:** ${b.documentation.collectionsWritten.join(', ') || '—'}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }
  return lines.join('\n');
}

export async function readCatalog(path: string): Promise<string> {
  try {
    return await readFile(path, 'utf8');
  } catch {
    return '';
  }
}

export async function writeCatalog(path: string, content: string): Promise<void> {
  await writeFile(path, content, 'utf8');
}
